const GOOGLE_SIGNIN_PROCEED='GOOGLE_SIGNIN_PROCEED';
const GOOGLE_SIGNIN_COMPLETE='GOOGLE_SIGNIN_COMPLETE';
const GOOGLE_SIGNOUT='GOOGLE_SIGNOUT';
const FETCH_USERS='FETCH_USERS';
const ERROR_WHILE_FETCH='ERROR_WHILE_FETCH';
const CONNECT_SOCKET='CONNECT_SOCKET';
const CURRENT_USER='CURRENT_USER';
const SEND_MESSAGE='SEND_MESSAGE';
const MESSAGE_RECIEVED='MESSAGE_RECIEVED'
const JOIN_ROOM='JOIN_ROOM'


export default {
    GOOGLE_SIGNIN_COMPLETE,GOOGLE_SIGNIN_PROCEED,GOOGLE_SIGNOUT,FETCH_USERS,ERROR_WHILE_FETCH,CONNECT_SOCKET,
    CURRENT_USER,SEND_MESSAGE,MESSAGE_RECIEVED,JOIN_ROOM
}