const GOOGLE_SIGNIN_PROCEED='GOOGLE_SIGNIN_PROCEED';
const GOOGLE_SIGNIN_COMPLETE='GOOGLE_SIGNIN_COMPLETE';
const GOOGLE_SIGNOUT='GOOGLE_SIGNOUT';

export default {
    GOOGLE_SIGNIN_COMPLETE,GOOGLE_SIGNIN_PROCEED,GOOGLE_SIGNOUT
}